title: AE Detect OCR Errors
description: This is an updated simple test add-on
type: object
documents: []
properties:
  name:
    project: Project
    type: integer
required:
  - project
categories: 
  - extraction
eventOptions:
  events:
    - upload
version: 2
