title: AE Detect OCR Errors
description: Add-On to detect OCR errors in AE documents
type: object
documents: []
properties:
  project:
    title: Project ID
    type: integer
  fix_errors:
    title: Fix errors
    type: boolean
    default: false
  fix_max_pages:
    title: Fix only if document has less than X pages (0 for no limit)
    type: integer
    default: 50
  fix_only_if_no_depts:
    title: Fix only if the documents has no tagged departments
    type: boolean
    default: true
required:
  - project
categories: 
  - extraction
version: 2

eventOptions:
  events:
    - upload